/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unidf.UI;

import br.unidf.DAL.CursosDAL;
import br.unidf.DTO.CursosDTO;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte
 */
public class frmCursos extends javax.swing.JFrame {

    /**
     * Creates new form frmCursos
     */
    public frmCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoIDCur = new javax.swing.JTextField();
        btnPesquisarCurID = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNomeCur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnderecoCur = new javax.swing.JTextField();
        btnIncluirCur = new javax.swing.JButton();
        btnAlterarCur = new javax.swing.JButton();
        btnExcluirCur = new javax.swing.JButton();
        btnMostrarTodosCur = new javax.swing.JButton();
        btnSairCur = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvCursos = new javax.swing.JTable();
        btnLimparCur = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cursos");
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Cadastro de Cursos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setText("Código(ID)");

        btnPesquisarCurID.setMnemonic('p');
        btnPesquisarCurID.setText("Pesquisar");
        btnPesquisarCurID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCurIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do Curso");

        jLabel4.setText("Endereço");

        btnIncluirCur.setMnemonic('A');
        btnIncluirCur.setText("Incluir");
        btnIncluirCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirCurActionPerformed(evt);
            }
        });

        btnAlterarCur.setMnemonic('E');
        btnAlterarCur.setText("Alterar");
        btnAlterarCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCurActionPerformed(evt);
            }
        });

        btnExcluirCur.setMnemonic('E');
        btnExcluirCur.setText("Excluir");
        btnExcluirCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCurActionPerformed(evt);
            }
        });

        btnMostrarTodosCur.setMnemonic('M');
        btnMostrarTodosCur.setText("Mostrar Todos");
        btnMostrarTodosCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosCurActionPerformed(evt);
            }
        });

        btnSairCur.setMnemonic('S');
        btnSairCur.setText("Sair");
        btnSairCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCurActionPerformed(evt);
            }
        });

        dgvCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código(ID)", "Curso", "Endereço"
            }
        ));
        dgvCursos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dgvCursosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dgvCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dgvCursos);

        btnLimparCur.setText("Limpar");
        btnLimparCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigoIDCur, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarCurID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluirCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterarCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarTodosCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimparCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSairCur)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtNomeCur)
            .addComponent(txtEnderecoCur, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoIDCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCurID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnderecoCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirCur)
                    .addComponent(btnAlterarCur)
                    .addComponent(btnExcluirCur)
                    .addComponent(btnMostrarTodosCur)
                    .addComponent(btnSairCur)
                    .addComponent(btnLimparCur))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirCurActionPerformed
       //Abrindo a conexão com o Banco de Dados
        CursosDAL dal = new CursosDAL();
        try
        {
            dal.abrirBD();
        }
        catch (Exception ex)
        {
           
        }
        // instanciando a classe CursosDTO do pacote DTO e criando seu objeto Curso
        CursosDTO Curso = new CursosDTO();
        Curso.setCurNome(txtNomeCur.getText());
        Curso.setCurEndereco(txtEnderecoCur.getText());
        // fazendo a validação dos dados
        if ((txtNomeCur.getText().isEmpty()) || (txtEnderecoCur.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Os campos não podem estar vazios !!!!");
            txtNomeCur.requestFocus();
        }
        else
        {
            try {
                // Instancia a classe CursosDAL e chama o método incluirCurso
                dal.incluirCurso(Curso);
                JOptionPane.showMessageDialog(null, "Usuário " + txtNomeCur.getText() + " incluído com sucesso! ");
                dal.fecharBD();
                txtNomeCur.requestFocus();
                btnMostrarTodosCur.setEnabled(true);
            } catch (Exception ex)
            {
               
            }
        }
        txtCodigoIDCur.setText("");
        txtEnderecoCur.setText("");
        txtNomeCur.setText("");


    }//GEN-LAST:event_btnIncluirCurActionPerformed

    private void btnSairCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCurActionPerformed
                // Fecha o formulário de Cursos e volta para o formulário principal
        dispose();

    }//GEN-LAST:event_btnSairCurActionPerformed

    private void btnAlterarCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCurActionPerformed
     // fazendo a validação dos dados, o método isEmpty que devolve true se a String for vazia ou false se a mesma nã estiver vazia
        if ((txtNomeCur.getText().isEmpty()) || (txtEnderecoCur.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Verifique Se Tem Algum Campo Vazio !!!!");
            //O cursor do mouse vai se posicionado no campo Código do Curso
            txtCodigoIDCur.requestFocus();
        }
        else 
        {
            // instanciando a classe CursosDTO do pacote DTO e criando seu objeto Curso
            CursosDTO Curso = new CursosDTO();
            // Instancia a classe CursosDAL 
            CursosDAL dal = new CursosDAL();
            Curso.setCurID((int) Long.parseLong(txtCodigoIDCur.getText()));
            Curso.setCurNome(txtNomeCur.getText());
            Curso.setCurEndereco(txtEnderecoCur.getText());
            try
            {
                // Chama o método alterarCurso da Classe CursosDAL
                dal.alterarCurso(Curso);
            }
            catch (Exception ex)
            {
                
            }
            JOptionPane.showMessageDialog(null, "Curso " + Curso.getCurNome() + " Alterado Com Sucesso !!!!");
        }

    }//GEN-LAST:event_btnAlterarCurActionPerformed

    private void btnExcluirCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCurActionPerformed
        
//Verifica se os campos estão preenchidos    
        if (((txtEnderecoCur.getText().isEmpty()) || (txtNomeCur.getText().isEmpty()) || (txtCodigoIDCur.getText().isEmpty()))) {
            JOptionPane.showMessageDialog(null, "Verifique Se Tem Algum Campo Vazio !!!!");
            txtCodigoIDCur.requestFocus();
        }
        else
        {
            // instanciando a classe CursosDTO do pacote DTO e criando seu objeto Curso        
            CursosDTO Curso = new CursosDTO();
            Curso.setCurID((int) Long.parseLong(txtCodigoIDCur.getText()));
            Object[] opcoes = {"Sim", "Não"};
            int contador = JOptionPane.showOptionDialog(null, "Deseja Excluir Este Curso: " + txtNomeCur.getText() + "?",
                    "Exclusão", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (contador == JOptionPane.YES_OPTION) {
                try
                {
                    CursosDAL dal = new CursosDAL();
                    dal.excluirCurso(Integer.parseInt(txtCodigoIDCur.getText()));
                    JOptionPane.showMessageDialog(null, "Curso Excluído com Sucesso !!!!");
                    // apaga os dados preenchidos nos campos de texto abaixo
                    txtCodigoIDCur.setText(null);
                    txtNomeCur.setText("");
                    txtEnderecoCur.setText("");
                    txtCodigoIDCur.requestFocus();
                }
                catch (Exception ex)
                {
                   
                }
            }
        }

    }//GEN-LAST:event_btnExcluirCurActionPerformed

    private void btnMostrarTodosCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosCurActionPerformed
         //Limpa todas as caixas de texto
        txtCodigoIDCur.setText("");
        txtEnderecoCur.setText("");
        txtNomeCur.setText("");
        // instanciando a classe CursosDAL
        CursosDAL Curso = new CursosDAL();
        //Cria a lista de todos os Cursos dentro da tabela Cursos
        List<CursosDTO> selecionaTodosCursos = new ArrayList<>();
        try
        {
            //Chama o método selecionaTodosCursos da Classe CursosDAL e preeche
            //o mesmo com a lista de todos os Cursos.
            selecionaTodosCursos = Curso.selecionarListaCursos();
        }
        catch (Exception ex)
        {
            
        }
        //Prepara a tabela para receber os dados da busca(Lista)
        DefaultTableModel tabm = (DefaultTableModel)dgvCursos.getModel();
        for(int contador = tabm.getRowCount()-1; contador >=0; contador--)
        {
            tabm.removeRow(contador);
        }
        int contador = 0;
        for(CursosDTO Cursos : selecionaTodosCursos)
        {
            //Mostra as informações dentro da Tabela
            tabm.addRow(new String[1]);
            dgvCursos.setValueAt(Cursos.getCurID(), contador, 0);
            dgvCursos.setValueAt(Cursos.getCurNome(),contador, 1);
            //Formata a data do banco, para localdate
            dgvCursos.setValueAt(Cursos.getCurEndereco(), contador, 2);        
            contador++;
        }
        //Limpa o campo Código do Curso
        txtCodigoIDCur.setText(null);
        //Posiciona o cursor do mouse no campo Nome do Curso
        txtNomeCur.requestFocus(); 

    }//GEN-LAST:event_btnMostrarTodosCurActionPerformed

    private void btnPesquisarCurIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCurIDActionPerformed
       //Verifica se o código do Curso está vazio
        if ("".equals(txtCodigoIDCur.getText()))
        {
            JOptionPane.showMessageDialog(null, "Código do Curso não pode ser vazio, favor digite um código válido !!!!");
            //Após a mensagem de erro, o foco do cursor vai ficar no campo Código do Curso
            txtCodigoIDCur.requestFocus();
        }
        else
        {
            //Faz o tratamento de erro, para verificar se a tabela Cursos está vazia
            try
            {
                // instanciando a classe CursosDTO do pacote DTO e criando seu objeto Curso
                CursosDTO Curso = new CursosDTO();
                // Instancia a classe CursosDAL
                CursosDAL dal = new CursosDAL();
                //Formatando a data para ser exibida no formato Brasileiro
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                Curso = dal.selecionarCursoPorID(Integer.valueOf(txtCodigoIDCur.getText()));
                //O botão Incluir vai ficar dsesabilitado
                btnIncluirCur.setEnabled(false);
                //O botão Alterar vai ficar habilitado
                btnAlterarCur.setEnabled(true);
                //O botão Excluir vai ficar habilitado
                btnExcluirCur.setEnabled(true);
                //O botão Mostrar Todos vai ficar habilitado
                btnMostrarTodosCur.setEnabled(true);
                //Mostra os dados do Curso pelo seu código
                txtNomeCur.setText(Curso.getCurNome());
                //Formatando a data do banco, para localdate
                txtEnderecoCur.setText(Curso.getCurEndereco());

            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Curso Não Encontrado. Favor Tente Novamente !!!!");
                txtCodigoIDCur.setText(null);
                txtCodigoIDCur.requestFocus();
            }
        }

    }//GEN-LAST:event_btnPesquisarCurIDActionPerformed

    private void dgvCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvCursosMouseClicked
        // Preenche o Grid com os dados gravados na tabela Cursos do MySQL
        //Formatando a data do banco, para localdate  
        int linhaSelecionada = dgvCursos.getSelectedRow();
        txtCodigoIDCur.setText(dgvCursos.getValueAt(linhaSelecionada, 0).toString());
        txtNomeCur.setText(dgvCursos.getValueAt(linhaSelecionada, 1).toString());
        txtEnderecoCur.setText(dgvCursos.getValueAt(linhaSelecionada, 2).toString());
        btnIncluirCur.setEnabled(false);
        btnAlterarCur.setEnabled(true);
        btnExcluirCur.setEnabled(true);

    }//GEN-LAST:event_dgvCursosMouseClicked

    private void btnLimparCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCurActionPerformed
        //Limpa os campos do formulário e do grid ou tabela 
        btnIncluirCur.setEnabled(true);
        btnAlterarCur.setEnabled(false);
        btnExcluirCur.setEnabled(false);
        btnMostrarTodosCur.setEnabled(true);
        txtCodigoIDCur.setText("");
        txtEnderecoCur.setText("");
        txtNomeCur.setText("");
        txtNomeCur.requestFocus();
        DefaultTableModel tabm = (DefaultTableModel)dgvCursos.getModel();
        for (int contador = tabm.getRowCount() -1; contador >= 0; contador--)
        {
            tabm.removeRow(contador);
        }

    }//GEN-LAST:event_btnLimparCurActionPerformed

    private void dgvCursosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dgvCursosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dgvCursosAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCur;
    private javax.swing.JButton btnExcluirCur;
    private javax.swing.JButton btnIncluirCur;
    private javax.swing.JButton btnLimparCur;
    private javax.swing.JButton btnMostrarTodosCur;
    private javax.swing.JButton btnPesquisarCurID;
    private javax.swing.JButton btnSairCur;
    private javax.swing.JTable dgvCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigoIDCur;
    private javax.swing.JTextField txtEnderecoCur;
    private javax.swing.JTextField txtNomeCur;
    // End of variables declaration//GEN-END:variables

    
}
