/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package br.unidf.UI;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Suporte
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        inserirIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFundoIpil = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuAplicativoIpil = new javax.swing.JMenu();
        itmSairlpil = new javax.swing.JMenuItem();
        mnuCadastrosCursos = new javax.swing.JMenu();
        itmCadCursos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imaginário Cursos multiCursos");
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);

        lblFundoIpil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unidf/UI/ipil.png"))); // NOI18N

        mnuAplicativoIpil.setMnemonic('f');
        mnuAplicativoIpil.setText("Aplicativo multicursos");

        itmSairlpil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSairlpil.setMnemonic('x');
        itmSairlpil.setText("Sair");
        itmSairlpil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairlpilActionPerformed(evt);
            }
        });
        mnuAplicativoIpil.add(itmSairlpil);

        menuBar.add(mnuAplicativoIpil);

        mnuCadastrosCursos.setText("Cadastros");

        itmCadCursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadCursos.setText("Cursos");
        itmCadCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadCursosActionPerformed(evt);
            }
        });
        mnuCadastrosCursos.add(itmCadCursos);

        menuBar.add(mnuCadastrosCursos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFundoIpil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFundoIpil)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmSairlpilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairlpilActionPerformed
                if (JOptionPane.showConfirmDialog(null, "Deseja Sair do Sistema?", "Aplicativo Ipil Ltda", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

    }//GEN-LAST:event_itmSairlpilActionPerformed

    private void itmCadCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadCursosActionPerformed
                //Verfica se o formulário é nulo e está visivel
        if ((frmCursos == null) || (!frmCursos.isVisible()))
        {
            frmCursos = new frmCursos();
            //jdpCadCli.add(frmCursos);
            frmCursos.setVisible(true);
        }
        
    }//GEN-LAST:event_itmCadCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadCursos;
    private javax.swing.JMenuItem itmSairlpil;
    private javax.swing.JLabel lblFundoIpil;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAplicativoIpil;
    private javax.swing.JMenu mnuCadastrosCursos;
    // End of variables declaration//GEN-END:variables

    private void inserirIcone() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconCurso.png")));
    }
private frmCursos frmCursos;
}
